### ISSUE TITLE
Allow user to set a custom URL

### ISSUE THREAD

**Issue by ChristianAEDev** [Yamazaki93/S3Uploader#2]
Hello @Yamazaki93,

I stumbled across this tool in the Electron apps sections. At first glance it looks like something I am looking for.
Sadly I am not using AWS but the S3 compatible https://www.minio.io/.
In theory these services are interchangeable. The problem is that I am not able to configure a custom URL for my credentials in S3Uploader.

I therefore would like to request the feature to be able to set a custom URL (per Account) to be able to use other S3 compatible providers.

Kind regards

**Comment by blackboxusa** [comment]
I second this

**Comment by dhhagan** [comment]
This would also be great so we could use all S3-compatible services. For example, Digital Ocean Spaces!

**Comment by blackboxusa** [comment]
Any update on this

**Comment by Yamazaki93** [comment]
Hi all, thanks for suggesting. I am currently swamped by my other obligations so probably can't get to it for a while. Meanwhile if anyone wants to take a stab at this issue feel free to fork this and open a repo.

**Comment by dhhagan** [comment]
@Yamazaki93 I may take a stab if I have some free time this weekend. Can you point to the section of the app that controls this?

**Comment by Yamazaki93** [comment]
@dhhagan certainly, any contribution is welcome. I've just been so busy with other things recently. So, the app basically uses aws nodejs api. 
The S3 part basically is separated into 2 fils, `aws.ts` for authentication and `s3.ts` for upload/download. If the services are S3 compatible, it should be fairly easy to switch them.
`job-manager.ts` tracks all the jobs that's in progress, again if the api is AWS/S3 compatible, that should not be too hairy to change. 
Hope this helps, let me know. I'll be happy to collaborate, but again I am pretty busy recently so probably only on weekends.
Cheers.

**Comment by Yamazaki93** [comment]
@dhhagan Found an opening this Sunday so started working on this. A new [https://github.com/Yamazaki93/S3Uploader/projects/1](project) is started to track this and a new branch `support-digital-ocean-space` is opened. Right now I think we can scope the workflow down to support DO space with a design that aims to support other S3 compatible services.

**Comment by dhhagan** [comment]
@Yamazaki93 that sounds great. I think the only thing that needs to change is the endpoint url - DO spaces is S3-compatible, so it should be super straight forward.

**Comment by Yamazaki93** [comment]
@dhhagan It turns out to be easier than I thought 👍. I've uploaded [0.2.0-rc.0](https://github.com/Yamazaki93/S3Uploader/releases/tag/v0.2.0-rc.0) which should support DO spaces, if you can test it and let me know if it works, I can roll out 0.2.0

**Comment by dhhagan** [comment]
@Yamazaki93 Awesome! Will do. I had some issues setting up the Electron environment when I tried, so didn't get too far..

**Comment by dhhagan** [comment]
@Yamazaki93 Actually, is there anyway to get the .dmg?

**Comment by Yamazaki93** [comment]
Ah that will come later tonight 😅 I have my Windows with me atm.

**Comment by Yamazaki93** [comment]
@dhhagan Ok the mac release is up now

**Comment by dhhagan** [comment]
Just tested and it works great!

**Comment by Yamazaki93** [comment]
Sounds good! Will close this issue and release it with 0.2.0
